import { formatDate } from '../utils/dateFormat';

export const resourceConfigs = {
  banners: {
    resource: 'banners',
    title: 'Quản lý Banner',
    description: 'Điều khiển banner trang chủ cho các chiến dịch và thông báo.',
    modalTitle: { create: 'Thêm banner', edit: 'Chỉnh sửa banner' },
    modalDescription: 'Điền thông tin banner dưới đây',
    submitLabel: { create: 'Thêm banner', edit: 'Lưu' },
    columns: [
      { key: 'image_url', label: 'Hình ảnh' },
      { key: 'title', label: 'Tiêu đề' },
      { key: 'cta_label', label: 'Nhãn CTA' },
      { key: 'priority', label: 'Độ ưu tiên' },
    ],
    formFields: [
      { name: 'title', label: 'Tiêu đề', required: true },
      { name: 'subtitle', label: 'Phụ đề' },
      { name: 'image_url', label: 'URL hình ảnh', type: 'url', required: true, placeholder: 'https://example.com/image.jpg', helpText: 'Nhập URL của hình ảnh banner' },
      { name: 'cta_label', label: 'Nhãn CTA' },
      { name: 'cta_link', label: 'Liên kết CTA', type: 'url', placeholder: 'https://example.com' },
      { name: 'priority', label: 'Độ ưu tiên', type: 'number', placeholder: '1' },
    ],
  },
  news: {
    resource: 'news',
    title: 'Quản lý Tin tức',
    description: 'Xuất bản và quản lý các bài viết tin tức cho cổng thông tin khoa.',
    modalTitle: { create: 'Thêm tin tức', edit: 'Chỉnh sửa tin tức' },
    modalDescription: 'Điền thông tin tin tức dưới đây',
    submitLabel: { create: 'Thêm tin tức', edit: 'Lưu' },
    columns: [
      { key: 'image_url', label: 'Hình ảnh' },
      { key: 'title', label: 'Tiêu đề' },
      { key: 'summary', label: 'Tóm tắt' },
      { key: 'published_at', label: 'Ngày xuất bản', render: (val) => val ? new Date(val).toLocaleDateString('vi-VN') : '-' },
    ],
    formFields: [
      { name: 'title', label: 'Tiêu đề', required: true },
      { name: 'summary', label: 'Tóm tắt', type: 'textarea', fullWidth: true },
      { name: 'content', label: 'Nội dung', type: 'textarea', required: true, fullWidth: true, rows: 6 },
      { name: 'image_url', label: 'URL hình ảnh', type: 'url', placeholder: 'https://example.com/image.jpg' },
      { name: 'published_at', label: 'Ngày xuất bản', type: 'date' },
    ],
  },
  events: {
    resource: 'events',
    title: 'Lịch sự kiện',
    description: 'Trưng bày các hội thảo, cuộc thi và hoạt động sinh viên.',
    modalTitle: { create: 'Thêm sự kiện', edit: 'Chỉnh sửa sự kiện' },
    modalDescription: 'Điền thông tin sự kiện dưới đây',
    submitLabel: { create: 'Thêm sự kiện', edit: 'Lưu' },
    columns: [
      { key: 'cover_image', label: 'Hình ảnh' },
      { key: 'title', label: 'Tiêu đề' },
      { key: 'event_date', label: 'Ngày', render: (val) => val ? new Date(val).toLocaleDateString('vi-VN') : '-' },
      { key: 'event_time', label: 'Giờ', render: (val) => val ? val : '-' },
      { key: 'location', label: 'Địa điểm' },
    ],
    formFields: [
      { name: 'title', label: 'Tiêu đề', required: true },
      { name: 'description', label: 'Mô tả', type: 'textarea', fullWidth: true },
      { name: 'event_date', label: 'Ngày sự kiện', type: 'date', required: true },
      { name: 'event_time', label: 'Giờ tổ chức', type: 'time', placeholder: 'HH:MM' },
      { name: 'location', label: 'Địa điểm' },
      { name: 'cover_image', label: 'URL hình ảnh bìa', type: 'url', placeholder: 'https://example.com/image.jpg' },
    ],
  },
  recruitment: {
    resource: 'recruitment',
    title: 'Bảng tuyển dụng',
    description: 'Quản lý các bài đăng tuyển dụng của khoa CNTT và doanh nghiệp.',
    modalTitle: { create: 'Thêm tin tuyển dụng', edit: 'Chỉnh sửa tin tuyển dụng' },
    modalDescription: 'Điền thông tin tuyển dụng dưới đây',
    submitLabel: { create: 'Thêm tin tuyển dụng', edit: 'Lưu' },
    columns: [
      { key: 'category', label: 'Loại', render: (val) => val === 'faculty' ? 'Tuyển dụng khoa' : 'Tuyển dụng doanh nghiệp' },
      { key: 'company_name', label: 'Công ty/Khoa' },
      { key: 'title', label: 'Tiêu đề' },
      { key: 'position', label: 'Vị trí' },
    ],
    formFields: [
      { 
        name: 'category', 
        label: 'Loại tuyển dụng', 
        type: 'select', 
        required: true,
        options: [
          { value: 'enterprise', label: 'Tuyển dụng doanh nghiệp' },
          { value: 'faculty', label: 'Tuyển dụng khoa' },
        ],
      },
      { name: 'company_name', label: 'Tên công ty/Khoa', required: true },
      { name: 'title', label: 'Tiêu đề công việc', required: true },
      { name: 'position', label: 'Vị trí' },
      { name: 'job_description', label: 'Mô tả công việc', type: 'textarea', fullWidth: true, rows: 5 },
      { name: 'contact_email', label: 'Email liên hệ', type: 'email', placeholder: 'contact@example.com' },
      { name: 'apply_link', label: 'Liên kết ứng tuyển', type: 'url', placeholder: 'https://example.com/apply' },
      { name: 'deadline', label: 'Hạn chót', type: 'date' },
    ],
  },
  enterprises: {
    resource: 'enterprises',
    title: 'Đối tác doanh nghiệp',
    description: 'Trưng bày các hợp tác chiến lược và đối tác doanh nghiệp.',
    columns: [
      { key: 'logo_url', label: 'Logo' },
      { key: 'name', label: 'Tên' },
      { key: 'industry', label: 'Lĩnh vực hợp tác' },
    ],
    formFields: [
      { name: 'name', label: 'Tên', required: true },
      { name: 'industry', label: 'Lĩnh vực hợp tác' },
      { name: 'description', label: 'Mô tả', type: 'textarea', required: true },
      { name: 'logo_url', label: 'URL logo', required: true },
      { name: 'address', label: 'Địa chỉ', required: true },
      { name: 'website', label: 'Website' },
      { name: 'partnership_date', label: 'Ngày hợp tác', type: 'date', required: true },
    ],
  },
  lecturers: {
    resource: 'lecturers',
    title: 'Danh mục Giảng viên',
    description: 'Duy trì thông tin liên hệ và chuyên môn.',
    modalTitle: { create: 'Thêm giảng viên', edit: 'Chỉnh sửa giảng viên' },
    modalDescription: 'Điền thông tin giảng viên dưới đây',
    submitLabel: { create: 'Thêm giảng viên', edit: 'Lưu' },
    columns: [
      { key: 'lecturer_code', label: 'Mã giảng viên' },
      { key: 'name', label: 'Tên' },
      { key: 'email', label: 'Email' },
      { key: 'academic_degree', label: 'Học vị' },
      { key: 'academic_rank', label: 'Học hàm' },
    ],
    formFields: [
      { name: 'lecturer_code', label: 'Mã giảng viên', required: true, placeholder: 'VD: LECT-0001' },
      { name: 'name', label: 'Họ và tên', required: true },
      { name: 'email', label: 'Email', type: 'email', required: true, placeholder: 'lecturer@university.edu' },
      { name: 'phone', label: 'Điện thoại', placeholder: '0123456789' },
      {
        name: 'academic_degree',
        label: 'Học vị',
        type: 'select',
        options: [
          { value: '', label: '-- Chọn học vị --' },
          { value: 'Cử nhân', label: 'Cử nhân' },
          { value: 'Thạc sĩ', label: 'Thạc sĩ' },
          { value: 'Tiến sĩ', label: 'Tiến sĩ' },
        ],
      },
      {
        name: 'academic_rank',
        label: 'Học hàm',
        type: 'select',
        options: [
          { value: '', label: '-- Chọn học hàm (tùy chọn) --' },
          { value: 'Phó Giáo sư', label: 'Phó Giáo sư' },
          { value: 'Giáo sư', label: 'Giáo sư' },
        ],
      },
      {
        name: 'research_direction',
        label: 'Hướng nghiên cứu',
        type: 'textarea',
        rows: 3,
        placeholder: 'VD: Trí tuệ nhân tạo, Học máy, Xử lý ngôn ngữ tự nhiên...',
      },
    ],
  },
  research: {
    resource: 'research',
    title: 'Dự án nghiên cứu',
    description: 'Tài liệu hóa các công trình khoa học, đồng tác giả và ngày xuất bản.',
    modalTitle: { create: 'Thêm dự án nghiên cứu', edit: 'Chỉnh sửa dự án nghiên cứu' },
    modalDescription: 'Điền thông tin dự án nghiên cứu dưới đây',
    submitLabel: { create: 'Thêm dự án', edit: 'Lưu' },
    columns: [
      { key: 'title', label: 'Tiêu đề' },
      { key: 'lead_lecturer', label: 'Giảng viên chủ trì' },
      { 
        key: 'publication_date', 
        label: 'Xuất bản',
        render: (value) => formatDate(value)
      },
    ],
    formFields: [
      { name: 'title', label: 'Tiêu đề', required: true },
      { name: 'research_period', label: 'Thời kỳ nghiên cứu', placeholder: 'VD: 2023-2024' },
      { name: 'publication_date', label: 'Ngày xuất bản', type: 'date' },
      { name: 'journal_name', label: 'Tên tạp chí', placeholder: 'VD: Journal of Computer Science, IEEE Transactions...' },
      { name: 'lead_lecturer', label: 'Giảng viên chủ trì' },
      { name: 'co_authors', label: 'Đồng tác giả', type: 'textarea', fullWidth: true, placeholder: 'Tên các đồng tác giả, phân cách bằng dấu phẩy' },
      { name: 'abstract', label: 'Tóm tắt', type: 'textarea', required: true, fullWidth: true, rows: 6 },
    ],
  },
  documents: {
    resource: 'student-documents',
    title: 'Tài liệu sinh viên',
    description: 'Biểu mẫu, quy định và hướng dẫn cho sinh viên.',
    modalTitle: { create: 'Thêm tài liệu', edit: 'Chỉnh sửa tài liệu' },
    modalDescription: 'Điền thông tin tài liệu dưới đây',
    submitLabel: { create: 'Thêm tài liệu', edit: 'Lưu' },
    columns: [
      { key: 'title', label: 'Tiêu đề' },
      { key: 'category', label: 'Danh mục' },
    ],
    formFields: [
      { name: 'title', label: 'Tiêu đề', required: true },
      {
        name: 'category',
        label: 'Danh mục',
        type: 'select',
        options: [
          { value: '', label: '-- Chọn danh mục --' },
          { value: 'Biểu mẫu', label: 'Biểu mẫu' },
          { value: 'Quy định', label: 'Quy định' },
          { value: 'Hướng dẫn', label: 'Hướng dẫn' },
          { value: 'Tài liệu tham khảo', label: 'Tài liệu tham khảo' },
        ],
      },
      { name: 'file_url', label: 'URL tệp', type: 'url', required: true, placeholder: 'https://example.com/document.pdf', helpText: 'Nhập URL của tệp tài liệu' },
      { name: 'description', label: 'Mô tả', type: 'textarea', fullWidth: true },
    ],
  },
  admissions: {
    resource: 'admissions',
    title: 'Thông tin tuyển sinh',
    description: 'Tiêu chí tuyển sinh hàng năm, chỉ tiêu và lịch trình.',
    modalTitle: { create: 'Thêm thông tin tuyển sinh', edit: 'Chỉnh sửa thông tin tuyển sinh' },
    modalDescription: 'Điền thông tin tuyển sinh dưới đây',
    submitLabel: { create: 'Thêm thông tin', edit: 'Lưu' },
    columns: [
      { key: 'title', label: 'Tiêu đề' },
      { key: 'admission_year', label: 'Năm' },
      { key: 'quota', label: 'Chỉ tiêu' },
    ],
    formFields: [
      { name: 'title', label: 'Tiêu đề', required: true },
      { name: 'admission_year', label: 'Năm', type: 'number', required: true, placeholder: '2024' },
      { name: 'description', label: 'Mô tả', type: 'textarea', fullWidth: true },
      { name: 'timeline', label: 'Lịch trình', type: 'textarea', fullWidth: true, placeholder: 'VD: Tháng 1-3: Nhận hồ sơ, Tháng 4: Thi tuyển...' },
      { name: 'quota', label: 'Chỉ tiêu', type: 'number', placeholder: '500' },
      { name: 'contact_point', label: 'Điểm liên hệ', placeholder: 'Email hoặc số điện thoại' },
    ],
  },
};
